// ITEM A: DECLARANDO VARIAVEL DE NOME

//const nome = "Daniel"

// ITEM B: DECLARANDO VARIAVEL DE IDADE

//let idade = 34

// ITEM C: IMPRIMINDO TIPO DE VARIAVEIS NA TELA

//console.log(typeof nome, typeof idade)

// ITEM D: A VARIAVEL "NOME" FOI IMPRESSA COMO STRING, POIS FOI DECLARADA COMO UM TEXTO ESCRITO ENTRE ASPAS. JÁ A VARIAVEL"IDADE" FOI DECLARADA COMO NUMBER POIS FOI DECLARADA COMO UM VALOR SEM ESTAR ESCRITO ENTRE ASPAS.

// ITEM E: ATUALIZANDO VARIAVEIS PARA PERGUNTAR AO USUARIO NOME E IDADE

const nome = prompt("Qual é o seu nome?")

let idade = prompt("Qual é a sua idade?")

// ITEM F: IMPRIMINDO TIPO DE VARIAVEIS NA TELA E COMENTANDO RESULTADO

console.log(typeof nome, typeof idade)

// AS DUAS VARIAVEIS FORAM IMPRESSAS NA TELA COMO STRING, MESMO A VARIAVEL "IDADE" SENDO UM VALOR NUMÉRICO.

// ITEM G: IMPRIMINDO MENSAGEM NA TELA

console.log("Olá", nome, "você tem", idade, "anos")






